# Define a 'Persistent Volume Claim'(PVC) for Mysql Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysqlpvc.name }} # name of PVC essential for identifying the storage data
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: {{ .Values.mysqlpvc.storage }}   #This will tell kubernetes about the amount of space we are trying to claim.