apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.usersdeployment.name }}
spec:
  selector:
    matchLabels:
      {{- include "users.labels" . | nindent 6 }}
  replicas: {{ .Values.usersdeployment.replicas }}
  template:
    metadata:
      labels:
        {{- include "users.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.usersdeployment.name }}
          image: "{{ .Values.usersdeployment.image }}:{{ .Values.usersdeployment.tag }}"
          ports:
            - containerPort: {{ .Values.usersdeployment.containerport }}
      restartPolicy: {{ .Values.usersdeployment.restartpolicy }}