apiVersion: v1
kind: Service
metadata:
  name: example-svc  # DNS name
  labels:
    app: example-svc
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:       # mysql Pod Should contain same labels
    app: example
    tier: database
  clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant
---
# Define a 'Persistent Volume Claim'(PVC) for Mysql Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: example
    tier: database
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi    #This will tell kubernetes about the amount of space we are trying to claim.
---
# Configure 'Deployment' of mysql server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app: example
    tier: database
spec:
  selector: # mysql Pod Should contain same labels
    matchLabels:
      app: example
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: example
        tier: database
    spec:
      containers:
        - image: mysql:latest # image from docker-hub
          #args:
            #- "--ignore-db-dir=lost+found" # Workaround for https://github.com/docker-library/mysql/issues/186
          name: example
          env:
            - name: MYSQL_ROOT_PASSWORD # Setting Root Password of mysql From a 'Secret'
              valueFrom:
                configMapKeyRef:
                  name: db-config # Name of the 'ConfigMap'
                  key: rootpass   # 'key' inside the ConfigMap which contains required 'value'
            - name: MYSQL_USER # Setting USER username on mysql From a 'Secret'
              valueFrom:
                configMapKeyRef:
                  name: db-config # Name of the 'ConfigMap'
                  key: user   # 'key' inside the ConfigMap which contains required 'value'
            - name: MYSQL_PASSWORD # Setting USER Password on mysql From a 'Secret'
              valueFrom:
                configMapKeyRef:
                  name: db-config # Name of the 'ConfigMap'
                  key: pass   # 'key' inside the ConfigMap which contains required 'value'
            - name: MYSQL_DATABASE # Setting Database Name from a 'ConfigMap'
              valueFrom:
                configMapKeyRef:
                  name: db-config # Name of the 'ConfigMap'
                  key: dbname   # 'key' inside the ConfigMap which contains required 'value'
          ports:
            - containerPort: 3306
              name: example
          volumeMounts:        # Mounting volume obtained from Persistent Volume Claim
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql #This is the path in the container on which the mounting will take place.
      volumes:
        - name: mysql-persistent-storage # Obtaining 'volume' from PVC
          persistentVolumeClaim:
            claimName: example-pv-claim