version: '3'
services:
    example:
        image: mysql:latest
        ports:
            - "3306:3306"
        container_name: example
        environment:
            MYSQL_ROOT_PASSWORD: "niranjan"
            MYSQL_DATABASE: "velotio"
            MYSQL_USER: "niranjan"
            MYSQL_PASSWORD: "niranjan"
        cap_add:
            - SYS_NICE
        volumes:
            - mysqltest:/var/lib/mysql
    usersapp:
        container_name: usersapp
        restart: always
        depends_on:
            - example
            - ordersapp
        links:
            - example
            - ordersapp
        image: users
        ports:
            - "5000:5000"
    ordersapp:
        container_name: ordersapp
        restart: always
        depends_on:
            - example
        links:
            - example
        image: orders
        ports:
            - "6000:6000"

volumes:
    mysqltest:
        driver: "local"